### ISSUE TITLE
Cannot edit text

### ISSUE THREAD

**Issue by bknill** [bfischer/react-inline-editing#1]
Hi, 

I'm using this as such

```
               <EditableLabel text={hotspot.title}
                    labelClassName='title'
                    inputClassName='title'
                    inputWidth='200px'
                    inputHeight='20px'
                    inputMaxLength={50}
                    onFocus={this._handleFocus}
                    onFocusOut={this._handleFocusOut}
                  />
```

But the label is not editable. No characters show when I type. The value comes from state. What am I missing?

**Comment by bknill** [comment]
Added 

```
     onChange={()=>{this._handleChangeEvent(this.state.hotspot.title)}}

  _handleChangeEvent(val) {
    return val
  }
```

Which worked

**Comment by bfischer** [comment]
Hey, sorry you're having this issue, but I'm glad you were able to find a work around for now. Still, I'll look more into this. When you clicked on the label, did it bring up the input editor, or did it the label not even response to the click event?

**Comment by bknill** [comment]
Hi it brings up input editor.. but cannot change text. It's something else React related I had this fixed without my hack and it's come back.

**Comment by bknill** [comment]
I have to hold the mouse down to edit it

**Comment by bknill** [comment]
It's because it's in a draggable. My bad.
